import Foundation

struct GitHubFileSnapshot:Hashable{let path:String;let sha:String;let content:String}
enum GitHubCodingServiceError:LocalizedError{case missingToken,invalidURL,invalidResponse,http(status:Int,message:String),nonTextFile,invalidPath;var errorDescription:String?{switch self{case .missingToken:return"Δεν υπάρχει GitHub token στις Ρυθμίσεις.";case .invalidURL:return"Μη έγκυρο GitHub API URL.";case .invalidResponse:return"Μη αναμενόμενη απάντηση από το GitHub API.";case .http(let status,let message):return"GitHub API HTTP \(status): \(message)";case .nonTextFile:return"Το GitHub αρχείο δεν αποκωδικοποιήθηκε ως UTF-8 text.";case .invalidPath:return"Μη ασφαλές repository path."}}}

/// Low-level transport for TRAVIS's own repository. Reads may be autonomous; writes are
/// only reachable from approved ProposedAction resolution and use SHA optimistic locking.
final class GitHubCodingService {
    static let shared=GitHubCodingService()
    let repository="georgalaskostas-alt/Travis_Multiplatform_Ai"
    private let session:URLSession
    private let defaults:UserDefaults
    private static let branchKey="travis.github.codingBranch"
    var branch:String{let configured=defaults.string(forKey:Self.branchKey)?.trimmingCharacters(in:.whitespacesAndNewlines);return configured?.isEmpty==false ? configured!:"agent/iphone-live-task-control"}
    init(session:URLSession = .shared,defaults:UserDefaults = .standard){self.session=session;self.defaults=defaults}
    func setBranch(_ value:String){let v=value.trimmingCharacters(in:.whitespacesAndNewlines);guard !v.isEmpty,!v.contains(".."),!v.hasPrefix("/"),!v.contains(" ") else{return};defaults.set(v,forKey:Self.branchKey)}
    func fetchFile(path:String)async throws->GitHubFileSnapshot{guard Self.safePath(path)else{throw GitHubCodingServiceError.invalidPath};let encoded=Self.encoded(path);guard var c=URLComponents(string:"https://api.github.com/repos/\(repository)/contents/\(encoded)")else{throw GitHubCodingServiceError.invalidURL};c.queryItems=[URLQueryItem(name:"ref",value:branch)];guard let url=c.url else{throw GitHubCodingServiceError.invalidURL};var request=URLRequest(url:url);request.setValue("application/vnd.github+json",forHTTPHeaderField:"Accept");request.setValue("2022-11-28",forHTTPHeaderField:"X-GitHub-Api-Version");if let token=Self.token(){request.setValue("Bearer \(token)",forHTTPHeaderField:"Authorization")};let(data,response)=try await session.data(for:request);try validate(response:response,data:data);guard let object=try JSONSerialization.jsonObject(with:data) as? [String:Any],let sha=object["sha"] as? String,let b64=object["content"] as? String,let decoded=Data(base64Encoded:b64.replacingOccurrences(of:"\n",with:"")),let text=String(data:decoded,encoding:.utf8)else{throw GitHubCodingServiceError.nonTextFile};return .init(path:path,sha:sha,content:text)}
    @discardableResult func replaceFile(path:String,expectedSHA:String,newContent:String,commitMessage:String)async throws->String{guard Self.safePath(path)else{throw GitHubCodingServiceError.invalidPath};guard let token=Self.token()else{throw GitHubCodingServiceError.missingToken};guard let url=URL(string:"https://api.github.com/repos/\(repository)/contents/\(Self.encoded(path))")else{throw GitHubCodingServiceError.invalidURL};var request=URLRequest(url:url);request.httpMethod="PUT";request.setValue("application/vnd.github+json",forHTTPHeaderField:"Accept");request.setValue("application/json",forHTTPHeaderField:"Content-Type");request.setValue("2022-11-28",forHTTPHeaderField:"X-GitHub-Api-Version");request.setValue("Bearer \(token)",forHTTPHeaderField:"Authorization");request.httpBody=try JSONSerialization.data(withJSONObject:["message":String(commitMessage.prefix(180)),"content":Data(newContent.utf8).base64EncodedString(),"sha":expectedSHA,"branch":branch]);let(data,response)=try await session.data(for:request);try validate(response:response,data:data);guard let object=try JSONSerialization.jsonObject(with:data) as? [String:Any],let commit=object["commit"] as? [String:Any],let sha=commit["sha"] as? String else{throw GitHubCodingServiceError.invalidResponse};return sha}
    private func validate(response:URLResponse,data:Data)throws{guard let http=response as? HTTPURLResponse else{throw GitHubCodingServiceError.invalidResponse};guard (200..<300).contains(http.statusCode)else{let msg=(try? JSONSerialization.jsonObject(with:data) as? [String:Any])?["message"] as? String ?? String(data:data,encoding:.utf8) ?? "unknown error";throw GitHubCodingServiceError.http(status:http.statusCode,message:msg)}}
    private static func token()->String?{let v=KeychainService.shared.githubToken?.trimmingCharacters(in:.whitespacesAndNewlines);return v?.isEmpty==false ? v:nil}
    private static func encoded(_ path:String)->String{path.split(separator:"/").map{String($0).addingPercentEncoding(withAllowedCharacters:.urlPathAllowed) ?? String($0)}.joined(separator:"/")}
    private static func safePath(_ path:String)->Bool{let p=path.trimmingCharacters(in:.whitespacesAndNewlines);return !p.isEmpty && !p.hasPrefix("/") && !p.contains("..") && !p.contains("\\") && !p.contains("\0")}
}
