import Foundation
struct TravisBridgeAlwaysOnJobSnapshot:Codable,Equatable,Identifiable{
    var id:UUID;var title:String;var kind:String;var state:String;var nextRunAt:Date?;var consecutiveFailures:Int;var lastError:String?;var isEnabled:Bool;var lastCompletedAt:Date?;var lastSummary:String?;var finalReport:String?;var completedSteps:Int?;var totalSteps:Int?;var checkpoint:String?;var recoveryCount:Int?
    var portfolioEquity:Double?;var portfolioCash:Double?;var dailyPnL:Double?;var realizedPnL:Double?;var unrealizedPnL:Double?;var winRate:Double?;var profitFactor:Double?;var drawdownPercent:Double?;var openPositions:Int?;var closedTrades:Int?
    var marketLeader:String?;var marketLeaderSignal:String?;var marketLeaderConfidence:Double?;var marketLeaderScore:Double?;var marketLeaderRSI:Double?;var marketLeader24h:Double?;var marketRegime:String?;var recentTradeAction:String?;var auditHigh:Int?;var auditMedium:Int?;var auditLow:Int?
    init(id:UUID,title:String,kind:String,state:String,nextRunAt:Date?,consecutiveFailures:Int,lastError:String?,isEnabled:Bool,lastCompletedAt:Date?=nil,lastSummary:String?=nil,finalReport:String?=nil,completedSteps:Int?=nil,totalSteps:Int?=nil,checkpoint:String?=nil,recoveryCount:Int?=nil,portfolioEquity:Double?=nil,portfolioCash:Double?=nil,dailyPnL:Double?=nil,realizedPnL:Double?=nil,unrealizedPnL:Double?=nil,winRate:Double?=nil,profitFactor:Double?=nil,drawdownPercent:Double?=nil,openPositions:Int?=nil,closedTrades:Int?=nil,marketLeader:String?=nil,marketLeaderSignal:String?=nil,marketLeaderConfidence:Double?=nil,marketLeaderScore:Double?=nil,marketLeaderRSI:Double?=nil,marketLeader24h:Double?=nil,marketRegime:String?=nil,recentTradeAction:String?=nil,auditHigh:Int?=nil,auditMedium:Int?=nil,auditLow:Int?=nil){self.id=id;self.title=title;self.kind=kind;self.state=state;self.nextRunAt=nextRunAt;self.consecutiveFailures=consecutiveFailures;self.lastError=lastError;self.isEnabled=isEnabled;self.lastCompletedAt=lastCompletedAt;self.lastSummary=lastSummary;self.finalReport=finalReport;self.completedSteps=completedSteps;self.totalSteps=totalSteps;self.checkpoint=checkpoint;self.recoveryCount=recoveryCount;self.portfolioEquity=portfolioEquity;self.portfolioCash=portfolioCash;self.dailyPnL=dailyPnL;self.realizedPnL=realizedPnL;self.unrealizedPnL=unrealizedPnL;self.winRate=winRate;self.profitFactor=profitFactor;self.drawdownPercent=drawdownPercent;self.openPositions=openPositions;self.closedTrades=closedTrades;self.marketLeader=marketLeader;self.marketLeaderSignal=marketLeaderSignal;self.marketLeaderConfidence=marketLeaderConfidence;self.marketLeaderScore=marketLeaderScore;self.marketLeaderRSI=marketLeaderRSI;self.marketLeader24h=marketLeader24h;self.marketRegime=marketRegime;self.recentTradeAction=recentTradeAction;self.auditHigh=auditHigh;self.auditMedium=auditMedium;self.auditLow=auditLow}
    var progressPercent:Int{guard let total=totalSteps,total>0 else{return state=="stopped" ? 100:0};return min(100,max(0,Int((Double(completedSteps ?? 0)/Double(total))*100)))}
}
struct TravisBridgeAlwaysOnSnapshot:Codable,Equatable{
    var workerHealthy:Bool;var workerPID:Int32?;var killSwitchEnabled:Bool;var jobsTotal:Int;var jobsActive:Int;var jobsFailed:Int;var summary:String;var jobs:[TravisBridgeAlwaysOnJobSnapshot];var workerGeneration:String?;var heartbeatAgeSeconds:Double?
    init(workerHealthy:Bool,workerPID:Int32?,killSwitchEnabled:Bool,jobsTotal:Int,jobsActive:Int,jobsFailed:Int,summary:String,jobs:[TravisBridgeAlwaysOnJobSnapshot],workerGeneration:String?=nil,heartbeatAgeSeconds:Double?=nil){self.workerHealthy=workerHealthy;self.workerPID=workerPID;self.killSwitchEnabled=killSwitchEnabled;self.jobsTotal=jobsTotal;self.jobsActive=jobsActive;self.jobsFailed=jobsFailed;self.summary=summary;self.jobs=jobs;self.workerGeneration=workerGeneration;self.heartbeatAgeSeconds=heartbeatAgeSeconds}
}
