import Foundation
import Observation

enum AutonomousMissionEngineV2State:String,Codable { case idle,planning,executing,correcting,waitingForApproval,completed,paused,failed,handedOff,hybrid }
struct AutonomousMissionV2Report:Codable,Hashable { let taskId:UUID;let state:AutonomousMissionEngineV2State;let planVersion:Int;let replansUsed:Int;let progress:Double;let message:String }
@MainActor @Observable final class AutonomousMissionEngineV2 {
 private let runtime:AgentTaskRuntime;private let executor:AgentTaskExecutor;private let orchestrator:AgentOrchestrator;private let planner:AutonomousMissionPlannerV2;private var reusedSkillByTask:[UUID:ReusableSkillStore.Skill]=[:]
 private(set)var state:AutonomousMissionEngineV2State = .idle;private(set)var activeTaskId:UUID?;private(set)var lastMessage="Ready";var onProgress:((String)->Void)?
 init(runtime:AgentTaskRuntime,executor:AgentTaskExecutor,orchestrator:AgentOrchestrator,planner:AutonomousMissionPlannerV2?=nil){self.runtime=runtime;self.executor=executor;self.orchestrator=orchestrator;self.planner=planner ?? AutonomousMissionPlannerV2()}
 @discardableResult func startMission(goal:String,title:String?=nil,priority:AgentTaskPriority = .medium,budget:TaskExecutionBudget = TaskExecutionBudget(),recentHistory:[ChatMessage]=[])async throws->AutonomousMissionV2Report{
  state = .planning;lastMessage="Σχεδιάζω την αποστολή…";onProgress?("🧠 TRAVIS: local memory first, cloud reasoning only when required.");let task=runtime.createTask(goal:goal,title:title,priority:priority,budget:budget);activeTaskId=task.id
  do{let mature=SkillExecutionEngine.shared.optimizedPlan(for:goal,capabilities:orchestrator.capabilities);let ids=Set(orchestrator.capabilities.map(\.id));let local=LocalMissionPlanReuse.makePlan(for:goal,from:runtime.tasks.filter{$0.id != task.id},availableCapabilityIds:ids);let plan:TaskPlan
   if let mature{plan=mature.plan;reusedSkillByTask[task.id]=mature.skill;onProgress?("⚡ LOCAL SKILL: χρησιμοποιώ ώριμη verified δεξιότητα χωρίς cloud planner.")}
   else if let local{plan=local.plan;LocalIntelligenceMetrics.shared.record(.learnedMissionPlan);onProgress?("🧠 LOCAL LEARNING: χρησιμοποιώ verified προηγούμενο σχέδιο χωρίς cloud planner.")}
   else{onProgress?("↗️ AI planner: αγοράζω reasoning επειδή δεν υπάρχει αρκετά αξιόπιστη local λύση.");plan=try await planner.makePlan(goal:goal,capabilities:orchestrator.capabilities,priorKnowledge:buildPriorExperienceContext(for:goal))}
   runtime.attachPlan(taskId:task.id,plan:plan);guard let planned=runtime.task(id:task.id)else{throw AgentTaskExecutorError.taskNotFound};let analysis=HeadlessMissionHandoff.analyze(task:planned)
   if analysis.isFullyHeadless {do{let h=try HeadlessMissionHandoff.export(task:planned);runtime.start(taskId:task.id);runtime.pause(taskId:task.id,reason:"HEADLESS OWNERSHIP · worker job \(h.jobID)");state = .handedOff;lastMessage="Η Mission V2 παραδόθηκε πλήρως στον Always-On worker (\(h.exportedSteps) steps). Μπορείς να κλείσεις το GUI.";onProgress?("♾️ HEADLESS HANDOFF: \(lastMessage)");return report(for:runtime.task(id:task.id) ?? planned,message:lastMessage)}catch HeadlessMissionHandoff.HandoffError.workerUnavailable{onProgress?("ℹ️ Worker offline· συνεχίζω foreground.")}catch{onProgress?("ℹ️ Headless export απέτυχε: \(error.localizedDescription). Συνεχίζω foreground.")}}
   else if analysis.isHybrid {onProgress?("🔀 HYBRID PLAN: \(analysis.foregroundStepIDs.count) foreground + \(analysis.headlessStepIDs.count) headless-safe steps. Εκτελώ foreground και επανελέγχω handoff σε κάθε checkpoint.")}
   runtime.start(taskId:task.id);state = analysis.isHybrid ? .hybrid:.executing;return try await continueMission(taskId:task.id,recentHistory:recentHistory)
  }catch{if let current=runtime.task(id:task.id),current.status == .pending || current.status == .planning{runtime.failTask(taskId:task.id,reason:"Mission planning failed: \(error.localizedDescription)")}else{runtime.pause(taskId:task.id,reason:"Mission planning failed: \(error.localizedDescription)")};state = .failed;lastMessage=error.localizedDescription;throw error}
 }
 @discardableResult func continueMission(taskId:UUID,recentHistory:[ChatMessage]=[])async throws->AutonomousMissionV2Report{
  activeTaskId=taskId;guard var task=runtime.task(id:taskId)else{state = .failed;throw AgentTaskExecutorError.taskNotFound};if task.status == .paused{runtime.resume(taskId:taskId);task=runtime.task(id:taskId) ?? task};if task.status == .pending{runtime.start(taskId:taskId)};var cycles=task.executionState.replanCount;let maxReplans=max(0,task.budget.maxReplans)
  while true{guard let current=runtime.task(id:taskId)else{state = .failed;throw AgentTaskExecutorError.taskNotFound};let analysis=HeadlessMissionHandoff.analyze(task:current)
   if analysis.isFullyHeadless && current.status != .completed {do{let h=try HeadlessMissionHandoff.export(task:current);runtime.pause(taskId:taskId,reason:"HEADLESS OWNERSHIP · worker job \(h.jobID)");state = .handedOff;lastMessage="Το υπόλοιπο της αποστολής παραδόθηκε στον Always-On worker (\(h.exportedSteps) steps).";onProgress?("♾️ HYBRID → HEADLESS: \(lastMessage)");return report(for:runtime.task(id:taskId) ?? current,message:lastMessage)}catch HeadlessMissionHandoff.HandoffError.workerUnavailable{onProgress?("ℹ️ Worker offline στο hybrid checkpoint· συνεχίζω foreground.")}catch{onProgress?("ℹ️ Hybrid handoff αναβλήθηκε: \(error.localizedDescription)")}}
   switch current.status{case .completed:finalizeLearning(taskId);state = .completed;lastMessage="Η αποστολή ολοκληρώθηκε, επαληθεύτηκε και αποθηκεύτηκε ως verified learning.";return report(for:current,message:lastMessage);case .waitingForApproval:state = .waitingForApproval;lastMessage="Χρειάζομαι έγκριση για ευαίσθητο βήμα.";return report(for:current,message:lastMessage);case .cancelled:state = .paused;lastMessage="Η αποστολή ακυρώθηκε.";return report(for:current,message:lastMessage);default:break}
   state = analysis.isHybrid ? .hybrid:.executing;let run=try await executor.executeUntilBlocked(taskId:taskId,recentHistory:recentHistory,maxStepsPerCycle:analysis.isHybrid ? 1:12);guard let after=runtime.task(id:taskId)else{state = .failed;throw AgentTaskExecutorError.taskNotFound}
   switch run.stopReason{case .completed:finalizeLearning(taskId);state = .completed;lastMessage="Η αποστολή ολοκληρώθηκε, επαληθεύτηκε και ενίσχυσε την τοπική γνώση.";return report(for:runtime.task(id:taskId) ?? after,message:lastMessage);case .waitingForApproval:state = .waitingForApproval;lastMessage="Η αποστολή περιμένει έγκριση.";return report(for:after,message:lastMessage);case .paused,.budgetExceeded:state = .paused;lastMessage=run.failureReason ?? after.failureReason ?? "Η αποστολή σταμάτησε με ασφάλεια.";return report(for:after,message:lastMessage);case .safetyStepLimitReached:runtime.checkpoint(taskId:taskId,summary:"Mission V2 checkpoint",nextAction:run.nextStepTitle);continue;case .noRunnableStep:if after.status == .running{state = .paused;lastMessage="Δεν υπάρχει εκτελέσιμο επόμενο βήμα."};fallthrough;case .failed:penalizeReusedSkill(taskId);guard cycles<maxReplans else{state = .failed;lastMessage=after.failureReason ?? "Εξαντλήθηκαν οι αυτόματες διορθώσεις.";return report(for:after,message:lastMessage)};cycles+=1;state = .correcting;do{let r=try await planner.makeRecoveryPlan(task:after,capabilities:orchestrator.capabilities);runtime.replacePlan(taskId:taskId,summary:r.summary,steps:r.steps);runtime.start(taskId:taskId);continue}catch{state = .failed;lastMessage="Απέτυχε η αυτόματη διόρθωση: \(error.localizedDescription)";runtime.pause(taskId:taskId,reason:lastMessage);return report(for:runtime.task(id:taskId) ?? after,message:lastMessage)}}
  }
 }
 func cancelActiveMission(reason:String="Cancelled by user"){guard let id=activeTaskId else{return};if !executor.requestCancellation(taskId:id,reason:reason){runtime.cancel(taskId:id,reason:reason)};state = .paused;lastMessage=reason}
 private func finalizeLearning(_ id:UUID){rewardReusedSkill(id);guard let task=runtime.task(id:id),task.status == .completed else{return};let projectId=ProjectWorkspaceStore.shared.project(containingTask:id)?.id;VerifiedLearningStore.shared.ingestCompletedTask(task,projectId:projectId);TravisLearningService.shared.refresh();LocalIntelligenceMetrics.shared.record(.learnedMissionPlan)}
 private func rewardReusedSkill(_ id:UUID){guard let s=reusedSkillByTask.removeValue(forKey:id)else{return};SkillConfidenceStore.shared.recordSuccess(skill:s)}
 private func penalizeReusedSkill(_ id:UUID){guard let s=reusedSkillByTask.removeValue(forKey:id)else{return};SkillConfidenceStore.shared.recordFailure(skill:s)}
 private func report(for task:AgentTask,message:String)->AutonomousMissionV2Report{.init(taskId:task.id,state:state,planVersion:task.plan.version,replansUsed:task.executionState.replanCount,progress:runtime.progress(taskId:task.id),message:message)}
 private func buildPriorExperienceContext(for goal:String)->String?{let words=Set(goal.lowercased().split{!$0.isLetter && !$0.isNumber}.map(String.init).filter{$0.count>=4});guard !words.isEmpty else{return nil};let similar=runtime.tasks.filter{$0.status == .completed || $0.status == .failed}.filter{t in let w=Set((t.title+" "+t.goal).lowercased().split{!$0.isLetter && !$0.isNumber}.map(String.init).filter{$0.count>=4});return !words.intersection(w).isEmpty}.prefix(4);guard !similar.isEmpty else{return nil};return similar.map{"PRIOR MISSION: \($0.title)\nSTATUS: \($0.status.rawValue)"}.joined(separator:"\n\n")}
}
