#if os(iOS)
import SwiftUI
struct iOSAlwaysOnWorkspace:View{@State private var bridge=TravisDeviceBridgeService.shared;@State private var confirm=false
private let cyan=Color(red:0.04,green:0.82,blue:1),panel=Color(red:0.004,green:0.042,blue:0.125)
var body:some View{ZStack{Color.black.ignoresSafeArea();ScrollView{VStack(spacing:12){header;stats;controls;jobs}.padding(14)}}.navigationTitle("Always-On").task{while !Task.isCancelled{if bridge.isConnected{bridge.requestStatus()};try? await Task.sleep(for:.seconds(2))}}.alert("Emergency stop?",isPresented:$confirm){Button("STOP ALL",role:.destructive){bridge.sendCommandToMac("/alwayson-kill")};Button("Cancel",role:.cancel){}}}
private var r:TravisBridgeAlwaysOnSnapshot?{bridge.lastStatus?.alwaysOn}
private var header:some View{HStack{Image(systemName:"server.rack").foregroundStyle(cyan);VStack(alignment:.leading){Text("ALWAYS-ON RUNTIME").bold();Text(r?.summary ?? "WAITING FOR MAC").font(.caption).foregroundStyle(r?.workerHealthy == true ? .green:.orange)};Spacer()}.padding().background(RoundedRectangle(cornerRadius:14).fill(panel))}
private var stats:some View{HStack{tile("WORKER",r?.workerHealthy == true ? "ONLINE":"OFFLINE",r?.workerHealthy == true ? .green:.red);tile("ACTIVE","\(r?.jobsActive ?? 0)",cyan);tile("FAILED","\(r?.jobsFailed ?? 0)",.orange)}}
private var controls:some View{HStack{Button{confirm=true}label:{Label("KILL SWITCH",systemImage:"exclamationmark.octagon.fill").frame(maxWidth:.infinity)}.buttonStyle(.borderedProminent).tint(.red);Button{bridge.sendCommandToMac("/alwayson-clear-kill")}label:{Text("CLEAR").frame(maxWidth:.infinity)}.buttonStyle(.bordered).tint(cyan)}}
@ViewBuilder private var jobs:some View{if let items=r?.jobs,!items.isEmpty{ForEach(items){j in VStack(alignment:.leading,spacing:8){HStack{VStack(alignment:.leading){Text(j.title).bold();Text("\(j.kind.uppercased()) · \(j.state.uppercased())").font(.caption2).foregroundStyle(.secondary)};Spacer()};if let e=j.lastError{Text(e).font(.caption2).foregroundStyle(.orange)};HStack{Button("PAUSE"){bridge.sendCommandToMac("/alwayson-pause \(j.id)")};Button("RESUME"){bridge.sendCommandToMac("/alwayson-resume \(j.id)")};Button("DELETE",role:.destructive){bridge.sendCommandToMac("/alwayson-delete \(j.id)")}}.buttonStyle(.bordered)}.padding().background(RoundedRectangle(cornerRadius:12).fill(panel))}}else{Text("No persistent jobs yet.").foregroundStyle(.secondary).padding(30)}}
private func tile(_ a:String,_ b:String,_ c:Color)->some View{VStack{Text(a).font(.caption2);Text(b).font(.caption.bold()).foregroundStyle(c)}.frame(maxWidth:.infinity).padding().background(RoundedRectangle(cornerRadius:10).fill(panel))}}
#endif
