#if os(iOS)
import SwiftUI

struct iOSAppShell: View {
    @Bindable var appState: TRAVISAppState
    @State private var activeSheet: MobileSheet?
    @State private var bridge = TravisDeviceBridgeService.shared
    private let cyan=Color(red:0.04,green:0.82,blue:1), navy=Color(red:0.001,green:0.018,blue:0.072), panel=Color(red:0.004,green:0.042,blue:0.125)

    var body: some View {
        NavigationStack { ZStack { LinearGradient(colors:[.black,navy,panel.opacity(0.85),navy],startPoint:.topLeading,endPoint:.bottomTrailing).ignoresSafeArea(); ScrollView { VStack(spacing:14){header;runtimeHero;quickAccess;missionPanel;devicePanel}.padding(14).padding(.bottom,90) } }.toolbar(.hidden,for:.navigationBar).safeAreaInset(edge:.bottom){bottomDock} }
        .preferredColorScheme(.dark)
        .task { bridge.start(); while !Task.isCancelled { if bridge.isConnected { bridge.requestStatus() }; try? await Task.sleep(for:.seconds(2)) } }
        .sheet(item:$activeSheet){ sheet in NavigationStack { sheetContent(sheet).toolbar { ToolbarItem(placement:.topBarTrailing){Button{activeSheet=nil}label:{Image(systemName:"xmark.circle.fill").foregroundStyle(cyan)}} } }.preferredColorScheme(.dark) }
    }
    private var header:some View{HStack{ZStack{RoundedRectangle(cornerRadius:12).fill(cyan.opacity(0.12)).frame(width:46,height:46);RoundedRectangle(cornerRadius:12).stroke(cyan,lineWidth:1.5).frame(width:46,height:46);Text("T").font(.title2.bold())};VStack(alignment:.leading){Text("TRAVIS").font(.title2.bold());Text("AI COMMAND CENTER").font(.caption2).foregroundStyle(.secondary)};Spacer();pill(bridge.isConnected ? "LINKED":"SEARCHING",bridge.isConnected ? .green:.orange)}.padding().hud(cyan,panel)}
    private var runtimeHero:some View{VStack(alignment:.leading,spacing:10){HStack{Label("ALWAYS-ON CORE",systemImage:"server.rack").font(.caption.bold());Spacer();if let r=bridge.lastStatus?.alwaysOn{pill(r.workerHealthy ? "ONLINE":"OFFLINE",r.workerHealthy ? .green:.red)}};if let r=bridge.lastStatus?.alwaysOn{HStack{tile("WORKER",r.workerHealthy ? "ONLINE":"OFFLINE",r.workerHealthy ? .green:.red);tile("ACTIVE","\(r.jobsActive)",cyan);tile("FAILED","\(r.jobsFailed)",.orange)};Text(r.summary).font(.caption).foregroundStyle(.secondary)}else{Text("Waiting for Mac runtime telemetry…").font(.caption).foregroundStyle(.secondary)};Button{activeSheet = .alwaysOn}label:{Label("OPEN ALWAYS-ON CONTROL",systemImage:"bolt.horizontal.circle.fill").frame(maxWidth:.infinity).padding(.vertical,10)}.buttonStyle(.borderedProminent).tint(cyan)}.padding().hud(cyan,panel)}
    private var quickAccess:some View{VStack(alignment:.leading,spacing:9){Text("QUICK ACCESS").font(.caption.bold());LazyVGrid(columns:[GridItem(.flexible()),GridItem(.flexible())],spacing:9){quick("CHAT","message.fill",.chat);quick("TASKS","checklist",.tasks);quick("NEW MISSION","plus.circle.fill",.mission);quick("ALWAYS-ON","server.rack",.alwaysOn);quick("HISTORY","clock.arrow.circlepath",.history);quick("PERMISSIONS","lock.shield.fill",.permissions)}}.padding().hud(cyan,panel)}
    private var missionPanel:some View{VStack(alignment:.leading,spacing:8){Label("CURRENT MISSION",systemImage:"scope").font(.caption.bold());Text(appState.isBusy ? "TRAVIS is executing an active task.":"No active mission").bold();Text(appState.lastResponseSummary.isEmpty ? "Ready for a new mission.":appState.lastResponseSummary).font(.caption).foregroundStyle(.secondary).lineLimit(4)}.frame(maxWidth:.infinity,alignment:.leading).padding().hud(cyan,panel)}
    private var devicePanel:some View{VStack(alignment:.leading,spacing:8){Label("DEVICE LINK",systemImage:"iphone.and.arrow.forward").font(.caption.bold());HStack{Text(bridge.connectedPeerName ?? "Searching for Mac TRAVIS").font(.caption);Spacer();pill(bridge.isConnected ? "CONNECTED":"SEARCHING",bridge.isConnected ? .green:.orange)};Button{bridge.start();bridge.requestStatus()}label:{Label("REFRESH MAC LINK",systemImage:"arrow.clockwise").frame(maxWidth:.infinity)}.buttonStyle(.bordered).tint(cyan)}.padding().hud(cyan,panel)}
    private var bottomDock:some View{HStack{dock("HOME","square.grid.2x2.fill",nil);dock("CHAT","message.fill",.chat);dock("TASKS","checklist",.tasks);dock("ALWAYS","server.rack",.alwaysOn);dock("SETTINGS","gearshape.fill",.settings)}.padding(10).background(.ultraThinMaterial)}
    @ViewBuilder private func sheetContent(_ s:MobileSheet)->some View{switch s{case .chat:iOSPremiumChatWorkspace(appState:appState);case .tasks:iOSLiveMacTasksWorkspace(appState:appState);case .mission:iOSPremiumMissionWorkspace(appState:appState);case .alwaysOn:iOSAlwaysOnWorkspace();case .history:ChatHistoryView(appState:appState).navigationTitle("History");case .permissions:PermissionsView(appState:appState).navigationTitle("Permissions");case .settings:SettingsView(appState:appState).navigationTitle("Settings")}}
    private func quick(_ t:String,_ i:String,_ s:MobileSheet)->some View{Button{activeSheet=s}label:{Label(t,systemImage:i).font(.caption.bold()).frame(maxWidth:.infinity,alignment:.leading).padding(11)}.buttonStyle(.plain).background(RoundedRectangle(cornerRadius:10).fill(.black.opacity(0.28))).overlay(RoundedRectangle(cornerRadius:10).stroke(cyan.opacity(0.25)))}
    private func dock(_ t:String,_ i:String,_ s:MobileSheet?)->some View{Button{activeSheet=s}label:{VStack{Image(systemName:i).foregroundStyle(cyan);Text(t).font(.system(size:7,weight:.bold))}.frame(maxWidth:.infinity)}.buttonStyle(.plain)}
    private func tile(_ a:String,_ b:String,_ c:Color)->some View{VStack(alignment:.leading){Text(a).font(.caption2).foregroundStyle(.secondary);Text(b).font(.caption.bold()).foregroundStyle(c)}.frame(maxWidth:.infinity,alignment:.leading).padding(9).background(RoundedRectangle(cornerRadius:9).fill(.black.opacity(0.25)))}
    private func pill(_ t:String,_ c:Color)->some View{HStack(spacing:5){Circle().fill(c).frame(width:6,height:6);Text(t).font(.caption2.bold())}.padding(.horizontal,8).padding(.vertical,5).background(Capsule().fill(c.opacity(0.12))).overlay(Capsule().stroke(c.opacity(0.5)))}
}
private enum MobileSheet:String,Identifiable{case chat,tasks,mission,alwaysOn,history,permissions,settings;var id:String{rawValue}}
private extension View{func hud(_ cyan:Color,_ panel:Color)->some View{background(RoundedRectangle(cornerRadius:16).fill(LinearGradient(colors:[.white.opacity(0.05),panel.opacity(0.96),.black.opacity(0.76)],startPoint:.topLeading,endPoint:.bottomTrailing))).overlay(RoundedRectangle(cornerRadius:16).stroke(cyan.opacity(0.35))).shadow(color:.black.opacity(0.7),radius:12,y:7)}}
#endif
